# ./docker-compose.yml

version: "3.1"

networks:
  orders-network:
    external: true
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    container_name: message-broker
    ports:
      - 5670:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - orders-network
    
