# ./docker-compose.yml

version: "3.1"

networks:
  main:
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: message-broker
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - main
    
